name = "milk-delivery-app"
main = "worker.js"
compatibility_date = "2026-04-21"

# Enable logs/metrics (optional but useful)
[observability]
enabled = true

# KV Namespace binding
[[kv_namespaces]]
binding = "MILK_DB"
id = "f1f1dfaaeba246e6a5357d9d1fe19aa1"
preview_id = "REPLACE_WITH_PREVIEW_ID"
