name = "milk-management"
main = "worker.js"
compatibility_date = "2024-01-01"

[assets]
directory = "./public"
binding = "ASSETS"

[[d1_databases]]
binding = "DB"
database_name = "milk_db"
database_id = "503995bf-23d9-4086-92cf-8c7117174d39"
