name = "milk-app"
main = "worker.js"
compatibility_date = "2026-04-21"

[observability]
enabled = true

[[d1_databases]]
binding = "DB"
database_name = "milk_db"
database_id = "503995bf-23d9-4086-92cf-8c7117174d39"

assets = { directory = "./public" }
